### ISSUE TITLE
'link is not defined' when create new post

### ISSUE THREAD

**Issue by foreseaz** [quietshu/innsbruck#1]
When save a post return "Internal Server Error" with error below: 
  
```
ReferenceError: link is not defined
      at Object.<anonymous> (../foreseaz.github.io/app/index.js:119:18)
      at next (native)
      at Object.<anonymous> (../foreseaz.github.io/node_modules/koa-route/index.js:34:19)
      at next (native)
      at Object.<anonymous> (../foreseaz.github.io/node_modules/koa-route/index.js:27:49)
      at next (native)
      at Object.<anonymous> (../foreseaz.github.io/node_modules/koa-route/index.js:27:49)
      at next (native)
      at Object.<anonymous> (../foreseaz.github.io/node_modules/koa-route/index.js:27:49)
      at next (native)

```

: D

**Comment by quietshu** [comment]
Thank you soooo much! That's a terrible typo... ;D
